name: Patch APK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Discord version"
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission
        run: chmod +x gen.sh
      - run: ./gen.sh ${{ github.event.inputs.version }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: discord apk
          path: /tmp/aliucord/apks/
        
      
